package.path = "/home/test/dotfiles/nvim/kotlin-module.nvim/lua/?.lua;/home/test/dotfiles/nvim/kotlin-module.nvim/lua/?/init.lua;"
  .. package.path

local validate = require("kotlin-module.validate")

describe("validate_module_name", function()
  it("accepts valid names", function()
    assert.is_nil(validate.validate_module_name("order-service"))
    assert.is_nil(validate.validate_module_name("lib"))
    assert.is_nil(validate.validate_module_name("foo2"))
  end)

  it("rejects empty", function()
    assert.is_not_nil(validate.validate_module_name(""))
    assert.is_not_nil(validate.validate_module_name(nil))
  end)

  it("rejects slashes, colons, whitespace", function()
    assert.is_not_nil(validate.validate_module_name("foo/bar"))
    assert.is_not_nil(validate.validate_module_name("a:b"))
    assert.is_not_nil(validate.validate_module_name("foo bar"))
  end)

  it("rejects leading dot and reserved names", function()
    assert.is_not_nil(validate.validate_module_name(".foo"))
    assert.is_not_nil(validate.validate_module_name("build"))
    assert.is_not_nil(validate.validate_module_name("gradle"))
    assert.is_not_nil(validate.validate_module_name("settings"))
    assert.is_not_nil(validate.validate_module_name("settings.gradle"))
    assert.is_not_nil(validate.validate_module_name("settings.gradle.kts"))
  end)

  it("rejects Windows reserved device names", function()
    assert.is_not_nil(validate.validate_module_name("CON"))
    assert.is_not_nil(validate.validate_module_name("con"))
    assert.is_not_nil(validate.validate_module_name("PRN"))
    assert.is_not_nil(validate.validate_module_name("AUX"))
    assert.is_not_nil(validate.validate_module_name("NUL"))
    assert.is_not_nil(validate.validate_module_name("COM1"))
    assert.is_not_nil(validate.validate_module_name("LPT9"))
  end)

  it("rejects trailing dots/spaces", function()
    assert.is_not_nil(validate.validate_module_name("foo."))
    assert.is_not_nil(validate.validate_module_name("foo "))
  end)
end)

describe("validate_package", function()
  it("accepts valid dotted identifiers", function()
    assert.is_nil(validate.validate_package("com.example"))
    assert.is_nil(validate.validate_package("com"))
    assert.is_nil(validate.validate_package("_foo.bar2"))
  end)

  it("rejects invalid packages", function()
    assert.is_not_nil(validate.validate_package(""))
    assert.is_not_nil(validate.validate_package(".com.example"))
    assert.is_not_nil(validate.validate_package("com.example."))
    assert.is_not_nil(validate.validate_package("com..example"))
    assert.is_not_nil(validate.validate_package("com.1foo"))
    assert.is_not_nil(validate.validate_package("com-example"))
  end)
end)

describe("package_to_path", function()
  it("converts dots to slashes", function()
    assert.equal("com/example", validate.package_to_path("com.example"))
  end)
end)

describe("module_collides", function()
  it("detects dir and include collisions", function()
    assert.is_not_nil(validate.module_collides("foo", { "foo" }, {}))
    assert.is_not_nil(validate.module_collides("foo", {}, { "foo" }))
    assert.is_nil(validate.module_collides("foo", { "bar" }, { "baz" }))
  end)
end)