require("config.foundation")
require("config.autocmds")
require("config.pack-hooks")
require("plugins")
require("config.nvim-hl")
require("statusline")
require("todos")
require("treesitter")
-- require("config.terminal")
