general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# keyboard dim (no monitor backlight available)
listener {
    timeout = 250
    on-timeout = brightnessctl -d input2::kana -s set 0
    on-resume = brightnessctl -d input2::kana -r
}
#
# # lock
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }
#
# DPMS off
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
