-- 1. shared deps (no theme depedency)
require("plugins.nvim-nio")
require("plugins.nui")
require("plugins.plenary")

-- 2. colorscheme (must be first — sets highlight groups)
require("plugins.catppuccin")

-- 3. UI plugins (depend on colorscheme highlights)
require("plugins.bufferline")
require("plugins.fidget")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.mini")
require("plugins.neogit")
require("plugins.neo-tree")
require("plugins.noice")
require("plugins.todo-comments")
require("plugins.which-key")

-- 4. Feature plugins (no UI theme dependency)
require("plugins.cmp")
require("plugins.conform")
require("plugins.dap")
require("plugins.guess-indent")
require("plugins.java")
require("plugins.kulala")
require("plugins.lsp")
require("plugins.neotest")
require("plugins.telescope")
require("plugins.treesitter")
