# Static theme: tokyo-night
set -g @thm_bg "#1a1b26"
set -g @thm_fg "#a9b1d6"
set -g @thm_rosewater "#a9b1d6"
set -g @thm_flamingo "#a9b1d6"
set -g @thm_pink "#bb9af7"
set -g @thm_mauve "#bb9af7"
set -g @thm_red "#f7768e"
set -g @thm_maroon "#f7768e"
set -g @thm_peach "#e0af68"
set -g @thm_yellow "#e0af68"
set -g @thm_green "#9ece6a"
set -g @thm_teal "#7dcfff"
set -g @thm_sky "#7dcfff"
set -g @thm_sapphire "#7aa2f7"
set -g @thm_blue "#7aa2f7"
set -g @thm_lavender "#7dcfff"
set -g @thm_subtext_1 "#9aa5ce"
set -g @thm_subtext_0 "#8b93b3"
set -g @thm_overlay_2 "#7b83a2"
set -g @thm_overlay_1 "#6a7391"
set -g @thm_overlay_0 "#565f89"
set -g @thm_surface_2 "#414868"
set -g @thm_surface_1 "#2f3346"
set -g @thm_surface_0 "#24283b"
set -g @thm_mantle "#16161e"
set -g @thm_crust "#15161e"
