font_family      NotoSans Nerd Font
font_size        12.0

background_opacity 0.8
hide_window_decorations yes

remember_window_size no
initial_window_width  1280
initial_window_height 640


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME