#!/usr/bin/env bash
# =============================================================================
# generate-static-theme.sh - Build a static theme from a color definition JSON
# =============================================================================
# Usage: generate-static-theme.sh <theme-definition.json> <output-dir>
#
# The JSON should have:
#   {
#     "name": "theme-name",
#     "wallpaper": "path or description",
#     "colors": {
#       "background": "#...", "foreground": "#...", "cursor": "#...",
#       "color0": "#..." through "color15": "#...",
#       "crust": "#...", "mantle": "#...", "base": "#...",
#       "surface0": "#...", "surface1": "#...", "surface2": "#...",
#       "overlay0": "#...", "overlay1": "#...", "overlay2": "#...",
#       "subtext0": "#...", "subtext1": "#...", "text": "#..."
#     }
#   }
# Tokens are read from ~/.config/themes/tokens.json
# =============================================================================

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <theme-definition.json> <output-dir>"
    exit 1
fi

DEFINITION="$1"
OUTPUT_DIR="$2"
TOKENS_FILE="$HOME/.config/themes/tokens.json"

if [[ ! -f "$DEFINITION" ]]; then
    echo "Error: $DEFINITION not found"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Export all colors as shell variables
eval "$(python3 -c "
import json
with open('$DEFINITION') as f:
    d = json.load(f)

out = []
for k, v in d.get('colors', d).items():
    k = k.upper().replace('-', '_')
    v = v.strip()
    if v and not v.startswith('#'):
        v = '#' + v
    out.append(f'{k}=\"{v}\"')
print('; '.join(out))
")"

# Derive aliases
BG="${BACKGROUND:-$COLOR0}"
FG="${FOREGROUND:-$COLOR7}"
CURSOR="${CURSOR:-$MAUVE}"
RED="${RED:-$COLOR1}"
GREEN="${GREEN:-$COLOR2}"
YELLOW="${YELLOW:-$COLOR3}"
BLUE="${BLUE:-$COLOR4}"
MAUVE="${MAUVE:-$COLOR5}"
TEAL="${TEAL:-$COLOR6}"
PINK="${PINK:-$COLOR5}"
MAROON="${MAROON:-$COLOR1}"
PEACH="${PEACH:-$COLOR3}"
SAPPHIRE="${SAPPHIRE:-$COLOR4}"
SKY="${SKY:-$COLOR6}"
LAVENDER="${LAVENDER:-$COLOR6}"
TEXT="${TEXT:-$FG}"
SURFACE0="${SURFACE0:-$COLOR0}"
SURFACE1="${SURFACE1:-$COLOR8}"
SURFACE2="${SURFACE2:-$COLOR7}"
CRUST="${CRUST:-$COLOR0}"
MANTLE="${MANTLE:-$COLOR0}"
BASE="${BASE:-$COLOR0}"
OVERLAY0="${OVERLAY0:-$COLOR7}"
OVERLAY1="${OVERLAY1:-$COLOR7}"
OVERLAY2="${OVERLAY2:-$COLOR7}"
SUBTEXT0="${SUBTEXT0:-$COLOR7}"
SUBTEXT1="${SUBTEXT1:-$COLOR7}"

# Default any empty color hexes
for var in COLOR0 COLOR1 COLOR2 COLOR3 COLOR4 COLOR5 COLOR6 COLOR7 \
           COLOR8 COLOR9 COLOR10 COLOR11 COLOR12 COLOR13 COLOR14 COLOR15 \
           BG FG CURSOR RED GREEN YELLOW BLUE MAUVE TEAL PINK MAROON PEACH \
           SAPPHIRE SKY LAVENDER TEXT CRUST MANTLE BASE SURFACE0 SURFACE1 \
           SURFACE2 OVERLAY0 OVERLAY1 OVERLAY2 SUBTEXT0 SUBTEXT1; do
    val="${!var:-}"
    if [[ -z "$val" || "$val" == '#' ]]; then
        eval "$var=\"#000000\""
    fi
done

# Load tokens
if [[ -f "$TOKENS_FILE" ]]; then
    FONT_SANS=$(python3 -c "import json; d=json.load(open('$TOKENS_FILE')); print(d.get('fonts', {}).get('sans', 'NotoSans Nerd Font'))")
    FONT_SIZE=$(python3 -c "import json; d=json.load(open('$TOKENS_FILE')); print(d.get('fonts', {}).get('size', '12px'))")
    FONT_SIZE_LARGE=$(python3 -c "import json; d=json.load(open('$TOKENS_FILE')); print(d.get('fonts', {}).get('size_large', '15px'))")
    W_RADIUS=$(python3 -c "import json; d=json.load(open('$TOKENS_FILE')); print(str(d.get('radii', {}).get('window', 0)))")
    S_TIGHT=$(python3 -c "import json; d=json.load(open('$TOKENS_FILE')); print(d.get('spacing', {}).get('tight', '4px'))")
else
    FONT_SANS="NotoSans Nerd Font"
    FONT_SIZE="12px"
    FONT_SIZE_LARGE="15px"
    W_RADIUS=0
    S_TIGHT="4px"
fi

THEME_NAME=$(python3 -c "import json; print(json.load(open('$DEFINITION')).get('name', 'unnamed'))" 2>/dev/null || echo "unnamed")
WP_NAME=$(python3 -c "import json; print(json.load(open('$DEFINITION')).get('wallpaper', 'static'))" 2>/dev/null || echo "static")

# === Generate theme.css ===
cat > "$OUTPUT_DIR/theme.css" << CSSEOF
/* Static theme: $THEME_NAME */
/* DO NOT EDIT - generated by generate-static-theme.sh */

@define-color background $BG;
@define-color foreground $FG;
@define-color cursor $CURSOR;

@define-color crust $CRUST;
@define-color mantle $MANTLE;
@define-color base $BASE;
@define-color surface0 $SURFACE0;
@define-color surface1 $SURFACE1;
@define-color surface2 $SURFACE2;
@define-color overlay0 $OVERLAY0;
@define-color overlay1 $OVERLAY1;
@define-color overlay2 $OVERLAY2;
@define-color subtext0 $SUBTEXT0;
@define-color subtext1 $SUBTEXT1;
@define-color text $TEXT;

@define-color red $RED;
@define-color maroon $MAROON;
@define-color peach $PEACH;
@define-color yellow $YELLOW;
@define-color green $GREEN;
@define-color teal $TEAL;
@define-color sky $SKY;
@define-color sapphire $SAPPHIRE;
@define-color blue $BLUE;
@define-color mauve $MAUVE;
@define-color pink $PINK;
@define-color lavender $LAVENDER;

@define-color color0 $COLOR0;
@define-color color1 $COLOR1;
@define-color color2 $COLOR2;
@define-color color3 $COLOR3;
@define-color color4 $COLOR4;
@define-color color5 $COLOR5;
@define-color color6 $COLOR6;
@define-color color7 $COLOR7;
@define-color color8 $COLOR8;
@define-color color9 $COLOR9;
@define-color color10 $COLOR10;
@define-color color11 $COLOR11;
@define-color color12 $COLOR12;
@define-color color13 $COLOR13;
@define-color color14 $COLOR14;
@define-color color15 $COLOR15;
CSSEOF

# === Generate colors.rasi ===
cat > "$OUTPUT_DIR/colors.rasi" << RASITMP
/* Static theme: $THEME_NAME */
* {
    background: $BG;
    foreground: $FG;
    background-color: $BG;
    border-color: $BG;
    separatorcolor: $BG;
    normal-foreground: $FG;
    normal-background: $SURFACE0;
    selected-normal-foreground: $MAUVE;
    selected-normal-background: $SURFACE1;
    alternate-normal-foreground: $FG;
    alternate-normal-background: $SURFACE0;
    overlay0: $OVERLAY0;
    overlay1: $OVERLAY1;
    overlay2: $OVERLAY2;
    surface0: $SURFACE0;
    surface1: $SURFACE1;
    surface2: $SURFACE2;
    subtext0: $SUBTEXT0;
    subtext1: $SUBTEXT1;
    urgent-foreground: $RED;
    urgent-background: $SURFACE0;
    selected-urgent-foreground: $MAUVE;
    selected-urgent-background: $SURFACE1;
    active-foreground: $GREEN;
    active-background: $SURFACE0;
    selected-active-foreground: $MAUVE;
    selected-active-background: $SURFACE1;
    font: "$FONT_SANS $FONT_SIZE";
    spacing: ${S_TIGHT/px/};
    border: 0;
    border-radius: $W_RADIUS;
    margin: 0;
    padding: 0;
}
RASITMP

# === Generate theme.lua ===
cat > "$OUTPUT_DIR/theme.lua" << LUAEOF
-- Static theme: $THEME_NAME

local theme = {}

theme.colors = {
    background = "${BG#\#}",
    foreground = "${FG#\#}",
    cursor = "${CURSOR#\#}",
    crust = "${CRUST#\#}",
    mantle = "${MANTLE#\#}",
    base = "${BASE#\#}",
    surface0 = "${SURFACE0#\#}",
    surface1 = "${SURFACE1#\#}",
    surface2 = "${SURFACE2#\#}",
    overlay0 = "${OVERLAY0#\#}",
    overlay1 = "${OVERLAY1#\#}",
    overlay2 = "${OVERLAY2#\#}",
    subtext0 = "${SUBTEXT0#\#}",
    subtext1 = "${SUBTEXT1#\#}",
    text = "${FG#\#}",
    red = "${RED#\#}",
    maroon = "${MAROON#\#}",
    peach = "${PEACH#\#}",
    yellow = "${YELLOW#\#}",
    green = "${GREEN#\#}",
    teal = "${TEAL#\#}",
    sky = "${SKY#\#}",
    sapphire = "${SAPPHIRE#\#}",
    blue = "${BLUE#\#}",
    mauve = "${MAUVE#\#}",
    pink = "${PINK#\#}",
    lavender = "${LAVENDER#\#}",
}

function theme.rgba(hex, alpha)
    alpha = alpha or "ee"
    return "rgba(" .. hex .. alpha .. ")"
end

return theme
LUAEOF

# === Generate kitty.conf ===
cat > "$OUTPUT_DIR/kitty.conf" << KITTYEOF
# Static theme: $THEME_NAME
font_family $FONT_SANS
font_size ${FONT_SIZE/px/}
foreground $FG
background $BG
cursor $MAUVE
selection_foreground $BG
selection_background $MAUVE
color0 $COLOR0
color1 $COLOR1
color2 $COLOR2
color3 $COLOR3
color4 $COLOR4
color5 $COLOR5
color6 $COLOR6
color7 $COLOR7
color8 $COLOR8
color9 $COLOR9
color10 $COLOR10
color11 $COLOR11
color12 $COLOR12
color13 $COLOR13
color14 $COLOR14
color15 $COLOR15
KITTYEOF

# === Generate waybar-fonts.css ===
cat > "$OUTPUT_DIR/waybar-fonts.css" << CSSEOF
/* Generated from tokens.json by generate-static-theme.sh */
* {
    font-size: ${FONT_SIZE_LARGE};
}
CSSEOF

# === Generate yazi.toml ===
cat > "$OUTPUT_DIR/yazi.toml" << YAZIEOF
# Static theme: $THEME_NAME
[app]
overall = { bg = "$BG" }
[mgr]
cwd = { fg = "$MAUVE" }
find_keyword = { fg = "$YELLOW", bold = true }
find_position = { fg = "$MAUVE" }
symlink_target = { fg = "$TEAL" }
marker_copied = { fg = "$GREEN" }
marker_cut = { fg = "$RED" }
marker_marked = { fg = "$MAUVE" }
marker_selected = { fg = "$BLUE" }
count_copied = { fg = "$GREEN" }
count_cut = { fg = "$RED" }
count_selected = { fg = "$BLUE" }
border_symbol = "│"
border_style = { fg = "$SURFACE1" }
[indicator]
parent = { bg = "$SURFACE0" }
current = { bg = "$SURFACE1" }
preview = { bg = "$SURFACE0" }
[tabs]
active = { fg = "$FG", bg = "$SURFACE1" }
inactive = { fg = "$SUBTEXT0", bg = "$CRUST" }
[mode]
normal_main = { fg = "$BG", bg = "$BLUE" }
normal_alt = { fg = "$FG", bg = "$SURFACE0" }
select_main = { fg = "$BG", bg = "$MAUVE" }
select_alt = { fg = "$FG", bg = "$SURFACE0" }
unset_main = { fg = "$BG", bg = "$TEAL" }
unset_alt = { fg = "$FG", bg = "$SURFACE0" }
[status]
overall = { bg = "$SURFACE0" }
perm_type = { fg = "$MAUVE" }
perm_read = { fg = "$GREEN" }
perm_write = { fg = "$YELLOW" }
perm_exec = { fg = "$RED" }
perm_sep = { fg = "$SUBTEXT0" }
progress_label = { fg = "$FG" }
progress_normal = { bg = "$SURFACE1" }
progress_error = { bg = "$RED" }
[which]
cols = 2
mask = { bg = "$SURFACE0" }
cand = { fg = "$MAUVE", bold = true }
rest = { fg = "$SUBTEXT0" }
desc = { fg = "$FG" }
separator = "  "
separator_style = { fg = "$SUBTEXT0" }
[confirm]
border = { fg = "$SURFACE1" }
title = { fg = "$MAUVE", bold = true }
body = { fg = "$FG" }
list = { fg = "$SUBTEXT1" }
btn_yes = { fg = "$GREEN" }
btn_no = { fg = "$RED" }
[spot]
border = { fg = "$SURFACE1" }
title = { fg = "$MAUVE" }
tbl_col = { fg = "$MAUVE" }
tbl_cell = { fg = "$FG" }
[notify]
title_info = { fg = "$BLUE", bold = true }
title_warn = { fg = "$YELLOW", bold = true }
title_error = { fg = "$RED", bold = true }
[pick]
border = { fg = "$SURFACE1" }
active = { fg = "$BG", bg = "$MAUVE" }
inactive = { fg = "$FG" }
[input]
border = { fg = "$SURFACE1" }
title = { fg = "$MAUVE" }
value = { fg = "$FG" }
selected = { fg = "$MAUVE", bold = true }
[cmp]
border = { fg = "$SURFACE1" }
active = { fg = "$BG", bg = "$MAUVE" }
inactive = { fg = "$FG" }
[tasks]
border = { fg = "$SURFACE1" }
title = { fg = "$MAUVE" }
hovered = { fg = "$BG", bg = "$MAUVE" }
[help]
on = { fg = "$MAUVE", bold = true }
run = { fg = "$FG" }
desc = { fg = "$SUBTEXT1" }
hovered = { fg = "$BG", bg = "$MAUVE" }
footer = { fg = "$SUBTEXT0" }
[filetype]
rules = [
    { mime = "image/*", fg = "$TEAL" },
    { mime = "{audio,video}/*", fg = "$MAUVE" },
    { mime = "inode/empty", fg = "$SUBTEXT0" },
    { mime = "text/*", fg = "$GREEN" },
    { mime = "application/gzip", fg = "$RED" },
    { mime = "application/zip", fg = "$RED" },
    { mime = "application/x-{tar,bzip*}*", fg = "$RED" },
    { mime = "application/pdf", fg = "$PEACH" },
    { url = "*/", fg = "$BLUE" },
    { url = "*", is = "orphan", fg = "$RED" },
]
YAZIEOF

# === Generate tmux-colors.conf ===
cat > "$OUTPUT_DIR/tmux-colors.conf" << TMUXEOF
# Static theme: $THEME_NAME
set -g @thm_bg "$BG"
set -g @thm_fg "$FG"
set -g @thm_rosewater "$TEXT"
set -g @thm_flamingo "$TEXT"
set -g @thm_pink "$COLOR5"
set -g @thm_mauve "$COLOR5"
set -g @thm_red "$COLOR1"
set -g @thm_maroon "$COLOR1"
set -g @thm_peach "$COLOR3"
set -g @thm_yellow "$COLOR3"
set -g @thm_green "$COLOR2"
set -g @thm_teal "$COLOR6"
set -g @thm_sky "$COLOR6"
set -g @thm_sapphire "$COLOR4"
set -g @thm_blue "$COLOR4"
set -g @thm_lavender "$COLOR6"
set -g @thm_subtext_1 "$SUBTEXT1"
set -g @thm_subtext_0 "$SUBTEXT0"
set -g @thm_overlay_2 "$OVERLAY2"
set -g @thm_overlay_1 "$OVERLAY1"
set -g @thm_overlay_0 "$OVERLAY0"
set -g @thm_surface_2 "$SURFACE2"
set -g @thm_surface_1 "$SURFACE1"
set -g @thm_surface_0 "$SURFACE0"
set -g @thm_mantle "$MANTLE"
set -g @thm_crust "$CRUST"
TMUXEOF

# === Generate nvim-colors.lua ===
cat > "$OUTPUT_DIR/nvim-colors.lua" << NVIMEOF
-- Static theme: $THEME_NAME
local M = {}

M.colors = {
    rosewater = "$TEXT",
    flamingo = "$TEXT",
    pink = "$COLOR5",
    mauve = "$MAUVE",
    red = "$RED",
    maroon = "$MAROON",
    peach = "$PEACH",
    yellow = "$YELLOW",
    green = "$GREEN",
    teal = "$TEAL",
    sky = "$SKY",
    sapphire = "$SAPPHIRE",
    blue = "$BLUE",
    lavender = "$LAVENDER",
    text = "$FG",
    subtext1 = "$SUBTEXT1",
    subtext0 = "$SUBTEXT0",
    overlay2 = "$OVERLAY2",
    overlay1 = "$OVERLAY1",
    overlay0 = "$OVERLAY0",
    surface2 = "$SURFACE2",
    surface1 = "$SURFACE1",
    surface0 = "$SURFACE0",
    base = "$BG",
    mantle = "$MANTLE",
    crust = "$CRUST",
}

function M.override(catppuccin_colors)
    for k, v in pairs(M.colors) do
        catppuccin_colors[k] = v
    end
    return catppuccin_colors
end

return M
NVIMEOF

# === Generate nvim-hl.lua ===
cat > "$OUTPUT_DIR/nvim-hl.lua" << NVIMHLEOF
-- Auto-generated neovim highlights: $THEME_NAME
return {
    bg         = "$BG",
    bg_alt     = "$SURFACE0",
    fg         = "$FG",
    fg_alt     = "$SUBTEXT0",
    accent     = "$MAUVE",
    muted      = "$SURFACE2",
    border     = "$SURFACE1",
    error      = "$RED",
    warning    = "$YELLOW",
    info       = "$GREEN",
    hint       = "$TEAL",
}
NVIMHLEOF

# === Generate metadata.json ===
cat > "$OUTPUT_DIR/metadata.json" << METAEOF
{
    "wallpaper": "$WP_NAME",
    "generated": "$(date -Iseconds)",
    "generator": "static",
    "theme_name": "$THEME_NAME",
    "mode": "dark",
    "overrides_applied": false
}
METAEOF

echo "Static theme '$THEME_NAME' generated in $OUTPUT_DIR"
